# Name:        update-asdf-versions.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will iterate through the .tool-versions file
#              and grab the latest version for each line, unless it is pinned
#              in the pin file. If there are changes to the .tool-versions file
#              the action will automatically tag a new version number.
name: Update asdf versions
on:
  schedule: # trigger daily at 06:40am PT (13:40UTC)
    - cron: '40 13 * * *'
jobs:
  build:
    name: Update asdf versions
    runs-on: self-hosted
    steps:
      - name: "Update asdf versions"
        env:
          REPO_EMAIL: ${{ secrets.REPO_EMAIL }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          REPO_OWNER: "mathew-fleisch"
          REPO_NAME: "tools"
          REPO_BRANCH: "main"
        # See the tools repo for more information: https://github.com/mathew-fleisch/tools
        run: ./scripts/update-asdf-to-latest.sh


